apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatapp-server
  namespace: chatapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatapp-server
  template:
    metadata:
      labels:
        app: chatapp-server
    spec:
      containers:
        - name: server
          image: annyo2024/chatapp-backend:v1.2
          ports:
            - containerPort: 4000
          env:
            - name: ALLOWED_ORIGINS
              value: "http://192.168.49.2:30000"

---

apiVersion: v1
kind: Service
metadata:
  name: chatapp-server-service
  namespace: chatapp
spec:
  type: NodePort
  selector:
    app: chatapp-server
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 31000
